actionTypes = {
  REQUEST_LOGIN: "REQUEST_LOGIN",
  RECEIVE_LOGIN: "RECEIVE_LOGIN",
  LOGOUT: "LOGOUT",

  REQUEST_SOCIAL_FEED: "REQUEST_SOCIAL_FEED",
  RECEIVE_SOCIAL_FEED: "RECEIVE_SOCIAL_FEED"
}

module.exports = actionTypes;
