actionTypes = {
  REQUEST_LOGIN: "REQUEST_LOGIN",
  RECEIVE_LOGIN: "RECEIVE_LOGIN",
  LOGOUT: "LOGOUT",

  REQUEST_SOCIAL_FEED: "REQUEST_SOCIAL_FEED",
  RECEIVE_SOCIAL_FEED: "RECEIVE_SOCIAL_FEED",
  REQUEST_PRIVATE_FEED: "REQUEST_PRIVATE_FEED",
  RECEIVE_PRIVATE_FEED: "RECEIVE_PRIVATE_FEED",
  REQUEST_PUBLIC_FEED: "REQUEST_PUBLIC_FEED",
  RECEIVE_PUBLIC_FEED: "RECEIVE_PUBLIC_FEED",

  REQUEST_CHARGES: "REQUEST_CHARGES",
  RECEIVE_CHARGES: "RECEIVE CHARGES",

  REQUEST_CHARGE_PAYMENT: "REQUEST_CHARGE_PAYMENT",
  RECEIVE_CHARGE_PAYMENT: "RECEIVE_CHARGE_PAYMENT",

  SWITCH_TO_SOCIAL_FEED: "SWITCH_TO_SOCIAL_FEED",
  SWITCH_TO_PUBLIC_FEED: "SWITCH_TO_PUBLIC_FEED",
  SWITCH_TO_PRIVATE_PROFILE: "SWITCH_TO_PRIVATE_PROFILE",

  REQUEST_USER_SEARCH: "REQUEST_USER_SEARCH",
  RECEIVE_USER_SEARCH: "RECEIVE_USER_SEARCH",
  CLEAR_USER_SEARCH: "CLEAR_USER_SEARCH",

  REQUEST_PAYMENT: "REQUEST_PAYMENT",
  RECEIVE_PAYMENT: "RECEIVE_PAYMENT",
  CLEAR_PAYMENT: "RECEIVE_PAYMENT",
}

module.exports = actionTypes;
